package dev.filetidy.autostart;

import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Locale;
import java.util.stream.Collectors;

/**
 * 管理开机自启项。
 * <p>
 * 各平台都用「用户级、可见、可手删」的常规位置，不写注册表、不动系统目录：
 * <ul>
 *   <li>Windows：启动文件夹里的 {@code filetidy.cmd}</li>
 *   <li>macOS：{@code ~/Library/LaunchAgents/dev.filetidy.plist}</li>
 *   <li>Linux：{@code ~/.config/autostart/filetidy.desktop}</li>
 * </ul>
 * 入口文件路径与命令行都可以注入，方便在临时目录里测试。
 */
public class AutostartManager {

    public enum Platform {
        WINDOWS, MACOS, LINUX
    }

    private static final String MARKER = "filetidy";

    private final Platform platform;
    private final Path entryFile;
    private final List<String> command;

    public AutostartManager(Platform platform, Path entryFile, List<String> command) {
        this.platform = platform;
        this.entryFile = entryFile;
        this.command = List.copyOf(command);
    }

    /** 按当前操作系统挑选默认位置。 */
    public static AutostartManager forCurrentUser(List<String> command) {
        Platform platform = currentPlatform();
        return new AutostartManager(platform, defaultEntryFile(platform), command);
    }

    public static Platform currentPlatform() {
        String os = System.getProperty("os.name", "").toLowerCase(Locale.ROOT);
        if (os.contains("win")) {
            return Platform.WINDOWS;
        }
        if (os.contains("mac")) {
            return Platform.MACOS;
        }
        return Platform.LINUX;
    }

    public static Path defaultEntryFile(Platform platform) {
        String home = System.getProperty("user.home", ".");
        return switch (platform) {
            case WINDOWS -> windowsStartupDirectory()
                    .resolve("Microsoft")
                    .resolve("Windows")
                    .resolve("Start Menu")
                    .resolve("Programs")
                    .resolve("Startup")
                    .resolve(MARKER + ".cmd");
            case MACOS -> Path.of(home, "Library", "LaunchAgents", "dev.filetidy.plist");
            case LINUX -> Path.of(home, ".config", "autostart", MARKER + ".desktop");
        };
    }

    private static Path windowsStartupDirectory() {
        String appData = System.getenv("APPDATA");
        if (appData != null && !appData.isBlank()) {
            return Path.of(appData);
        }
        return Path.of(System.getProperty("user.home", "."), "AppData", "Roaming");
    }

    public Platform platform() {
        return platform;
    }

    public Path entryFile() {
        return entryFile;
    }

    public List<String> command() {
        return command;
    }

    public boolean isEnabled() {
        return Files.isRegularFile(entryFile);
    }

    /** 写入自启入口文件，返回实际写入的路径。 */
    public Path enable() throws IOException {
        Path parent = entryFile.getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }
        Files.writeString(entryFile, render(), charset());
        return entryFile;
    }

    /**
     * 删除自启入口文件。只删这一个固定名字的文件，不做任何递归操作。
     *
     * @return 是否真的删掉了东西
     */
    public boolean disable() throws IOException {
        return Files.deleteIfExists(entryFile);
    }

    /** 渲染入口文件内容。纯函数，便于直接对三种平台断言。 */
    String render() {
        return switch (platform) {
            case WINDOWS -> windowsScript();
            case MACOS -> macPlist();
            case LINUX -> linuxDesktopEntry();
        };
    }

    /**
     * Windows 的 .cmd 由 cmd.exe 按控制台代码页逐字节读取，所以要用系统本地编码写，
     * 否则路径里一旦有中文就会乱码导致自启失败。
     */
    private Charset charset() {
        if (platform != Platform.WINDOWS) {
            return StandardCharsets.UTF_8;
        }
        String nativeEncoding = System.getProperty("native.encoding");
        if (nativeEncoding == null || nativeEncoding.isBlank()) {
            return StandardCharsets.UTF_8;
        }
        try {
            return Charset.forName(nativeEncoding);
        } catch (RuntimeException e) {
            return StandardCharsets.UTF_8;
        }
    }

    private String windowsScript() {
        String line = command.stream().map(AutostartManager::quoteWindows).collect(Collectors.joining(" "));
        // cmd.exe 对 LF 结尾的批处理容错有限，统一写成 CRLF
        return """
                @echo off
                rem Generated by filetidy autostart. Delete this file to disable autostart.
                start "" /min %s
                """.formatted(line).replace("\n", "\r\n");
    }

    private String macPlist() {
        String arguments = command.stream()
                .map(arg -> "    <string>" + xmlEscape(arg) + "</string>")
                .collect(Collectors.joining(System.lineSeparator()));
        return """
                <?xml version="1.0" encoding="UTF-8"?>
                <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
                <plist version="1.0">
                <dict>
                  <key>Label</key>
                  <string>dev.filetidy</string>
                  <key>ProgramArguments</key>
                  <array>
                %s
                  </array>
                  <key>RunAtLoad</key>
                  <true/>
                  <key>KeepAlive</key>
                  <false/>
                </dict>
                </plist>
                """.formatted(arguments);
    }

    private String linuxDesktopEntry() {
        String exec = command.stream().map(AutostartManager::quoteDesktop).collect(Collectors.joining(" "));
        return """
                [Desktop Entry]
                Type=Application
                Name=filetidy
                Comment=Tidy a folder by rules
                Exec=%s
                Terminal=false
                X-GNOME-Autostart-enabled=true
                """.formatted(exec);
    }

    /** cmd.exe 里会拆参数或触发转义的字符（不含引号，引号单独处理）。 */
    private static final String WINDOWS_SPECIALS = "&()[]{}^=;!'+,`~|<>";

    /** freedesktop 规范里在引号内有特殊含义、或在引号外会被拆分的字符。 */
    private static final String DESKTOP_SPECIALS = "&|<>()$`'\"\\";

    /**
     * 只在需要时加引号，这样生成出来的文件人读起来清爽。
     * <p>
     * .cmd 里反斜杠不是转义符，所以不能像 shell 那样把 {@code \} 成对写；
     * 而 .desktop 的引号内 {@code \}、{@code $}、{@code `} 需要转义，两者规则不同。
     */
    private static String quoteWindows(String value) {
        return needsQuotes(value, WINDOWS_SPECIALS) ? "\"" + value.replace("\"", "\\\"") + "\"" : value;
    }

    private static String quoteDesktop(String value) {
        if (!needsQuotes(value, DESKTOP_SPECIALS)) {
            return value;
        }
        String escaped = value.replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("`", "\\`")
                .replace("$", "\\$");
        return "\"" + escaped + "\"";
    }

    private static boolean needsQuotes(String value, String specials) {
        return value.isEmpty() || value.chars().anyMatch(c -> Character.isWhitespace(c) || specials.indexOf(c) >= 0);
    }

    private static String xmlEscape(String value) {
        return value.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;");
    }
}
